-- Hand-written, not generated by drizzle-kit (same reasoning as 0001).
--
-- Enables Supabase Realtime for `rooms` and `room_participants`, and adds
-- the minimum RLS policy that requires: Realtime's `postgres_changes`
-- feature only delivers change events to a client if RLS on that table
-- would let that client SELECT the row — a deny-all table (0001's state)
-- silently delivers nothing, no error, which is why this needs its own
-- migration rather than just a client-side subscribe call.
--
-- The policy below is public read (`USING (true)`), which sounds looser
-- than it is: the app's only access control is knowing a room's 6-character
-- code, and `GET /api/rooms/[code]` already returns this exact same data
-- (room + participant list) to anyone, unauthenticated, who has the code.
-- This policy doesn't expose anything that route doesn't already. Writes
-- are unaffected — those still only happen server-side via DATABASE_URL,
-- which connects as the DB owner role and bypasses RLS entirely.
--
-- Revisit when rooms grow real privacy tiers (the `privacy` column on
-- `rooms` exists but isn't enforced anywhere yet) — this policy would need
-- to become conditional at that point.

CREATE POLICY "Public read (realtime)" ON "rooms" FOR SELECT USING (true);
CREATE POLICY "Public read (realtime)" ON "room_participants" FOR SELECT USING (true);

ALTER PUBLICATION supabase_realtime ADD TABLE "rooms";
ALTER PUBLICATION supabase_realtime ADD TABLE "room_participants";
