-- Hand-written, not generated by drizzle-kit (same reasoning as 0001/0002 —
-- no schema.ts diff behind this one; `messages` has existed since Phase 0–1).
--
-- Same pattern as 0002_realtime_rooms.sql: Realtime's `postgres_changes`
-- only delivers an event to a client if RLS would let that client SELECT
-- the row, so chat needs its own public-read policy + publication entry,
-- same reasoning as rooms/room_participants — a room code is still the
-- only access control this app has, and nothing about chat messages is
-- more sensitive than the room roster that's already public-read.
--
-- Revisit alongside 0002's policy once rooms grow real privacy tiers.

CREATE POLICY "Public read (realtime)" ON "messages" FOR SELECT USING (true);

ALTER PUBLICATION supabase_realtime ADD TABLE "messages";
