-- Hand-written, not generated by drizzle-kit (same reasoning as 0001/0002/0004
-- — no schema.ts diff behind this one; picks/pick_options/pick_entries have
-- existed since Phase 0-1).
--
-- Same pattern as 0002/0004: Realtime's `postgres_changes` only delivers an
-- event to a client if RLS would let that client SELECT the row, so Picks
-- needs the same public-read policy + publication membership as rooms and
-- chat. Same reasoning as those: a room code is still the only access
-- control this app has, and nothing here is more sensitive than the roster
-- or chat that are already public-read.

CREATE POLICY "Public read (realtime)" ON "picks" FOR SELECT USING (true);
CREATE POLICY "Public read (realtime)" ON "pick_options" FOR SELECT USING (true);
CREATE POLICY "Public read (realtime)" ON "pick_entries" FOR SELECT USING (true);

ALTER PUBLICATION supabase_realtime ADD TABLE "picks";
ALTER PUBLICATION supabase_realtime ADD TABLE "pick_options";
ALTER PUBLICATION supabase_realtime ADD TABLE "pick_entries";
